name: 🐛 Bug Report
description: Report something that isn't working as expected
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below to help us reproduce the issue.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using?
      placeholder: ex. v0.1.0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's the bug?
      placeholder: A clear and concise description...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the problem?
      placeholder: |
        1. Run '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: It should have...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs or Screenshots
      description: Paste logs or add screenshots
      render: shell
    validations:
      required: false
